//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapgenix.Canvas.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionDescription {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionDescription() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mapgenix.Canvas.Properties.ExceptionDescription", typeof(ExceptionDescription).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not CloneDeep because the object is open or drawing, please close or end drawing first..
        /// </summary>
        internal static string CheckIsOpenedWhenCloneDeep {
            get {
                return ResourceManager.GetString("CheckIsOpenedWhenCloneDeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The color you have provided does not exist..
        /// </summary>
        internal static string ColorDoesNotExist {
            get {
                return ResourceManager.GetString("ColorDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CurrentExtent property must be set before calling this method. If you want to use a custom extent, please use the static method.
        /// </summary>
        internal static string CurrentExtentNotAssigned {
            get {
                return ResourceManager.GetString("CurrentExtentNotAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are trying to use both a default style and the custom styles collection.  You may only use one or the other..
        /// </summary>
        internal static string DefaultAndCustomStyleDuplicate {
            get {
                return ResourceManager.GetString("DefaultAndCustomStyleDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input double value is out of range..
        /// </summary>
        internal static string DoubleOutOfRange {
            get {
                return ResourceManager.GetString("DoubleOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for the enumeration is not on of the valid values..
        /// </summary>
        internal static string EnumerationOutOfRange {
            get {
                return ResourceManager.GetString("EnumerationOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Feature you provided is not valid..
        /// </summary>
        internal static string FeatureIsNotValid {
            get {
                return ResourceManager.GetString("FeatureIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GDI+ threw a status error code..
        /// </summary>
        internal static string GdipLoadImageFromFileError {
            get {
                return ResourceManager.GetString("GdipLoadImageFromFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The GeoCanvas is currently not drawing.  Please call the BeginDraw method before calling this method..
        /// </summary>
        internal static string GeocanvasIsNotInDrawing {
            get {
                return ResourceManager.GetString("GeocanvasIsNotInDrawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input string HtmlColor is invalid..
        /// </summary>
        internal static string HtmlColorIsInvalid {
            get {
                return ResourceManager.GetString("HtmlColorIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image property can&apos;t be null..
        /// </summary>
        internal static string ImageInPointStyleCanNotBeNull {
            get {
                return ResourceManager.GetString("ImageInPointStyleCanNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ImageScaled property must be larger than 0..
        /// </summary>
        internal static string ImageScaleShouldBiggerThanZero {
            get {
                return ResourceManager.GetString("ImageScaleShouldBiggerThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is not supported now for projection..
        /// </summary>
        internal static string IsNotSupportedNowForProjection {
            get {
                return ResourceManager.GetString("IsNotSupportedNowForProjection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not support KeyColor in the specify GeoCanvas..
        /// </summary>
        internal static string KeyColorIsNotSupported {
            get {
                return ResourceManager.GetString("KeyColorIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number should be between 0 and 255.
        /// </summary>
        internal static string NumberShouldBeByte {
            get {
                return ResourceManager.GetString("NumberShouldBeByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter you supplied may not be empty..
        /// </summary>
        internal static string ParameterIsEmpty {
            get {
                return ResourceManager.GetString("ParameterIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter you supplied may not be null..
        /// </summary>
        internal static string ParameterIsNull {
            get {
                return ResourceManager.GetString("ParameterIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projection initialization failed..
        /// </summary>
        internal static string ProjectionInitializationError {
            get {
                return ResourceManager.GetString("ProjectionInitializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The projection is not open.  Please open it before calling this method..
        /// </summary>
        internal static string ProjectionIsNotOpen {
            get {
                return ResourceManager.GetString("ProjectionIsNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The shape you provided does not pass our simple validation..
        /// </summary>
        internal static string ShapeIsInvalidForOperation {
            get {
                return ResourceManager.GetString("ShapeIsInvalidForOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Shape Is Not Valid Type..
        /// </summary>
        internal static string TargetShapeIsNotValidType {
            get {
                return ResourceManager.GetString("TargetShapeIsNotValidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value should be greater than zero..
        /// </summary>
        internal static string TheValueShouldBeGreaterThanZero {
            get {
                return ResourceManager.GetString("TheValueShouldBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format of the well known binary is incorrect..
        /// </summary>
        internal static string WkbIsInvalid {
            get {
                return ResourceManager.GetString("WkbIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The well known binary is not valid for drawing..
        /// </summary>
        internal static string WkbIsNotValidForDrawing {
            get {
                return ResourceManager.GetString("WkbIsNotValidForDrawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The world extent is not valid..
        /// </summary>
        internal static string WorldExtentIsNotValid {
            get {
                return ResourceManager.GetString("WorldExtentIsNotValid", resourceCulture);
            }
        }
    }
}
