//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapgenix.Shapes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionDescription {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionDescription() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mapgenix.Shapes.Properties.ExceptionDescription", typeof(ExceptionDescription).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The decimal degree latitude value you provided was out of range..
        /// </summary>
        internal static string DecimalDegreeLatitudeOutOfRange {
            get {
                return ResourceManager.GetString("DecimalDegreeLatitudeOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The decimal degree longitude value you provided was out of range..
        /// </summary>
        internal static string DecimalDegreeLongitudeOutOfRange {
            get {
                return ResourceManager.GetString("DecimalDegreeLongitudeOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The degreesMinutesSeconds string may not be null or empty..
        /// </summary>
        internal static string DecimalDegreeSecondsStringNull {
            get {
                return ResourceManager.GetString("DecimalDegreeSecondsStringNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DegreesMinutesSeconds value is invalid..
        /// </summary>
        internal static string DegreesMinutesSecondsInputError {
            get {
                return ResourceManager.GetString("DegreesMinutesSecondsInputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input double value is out of range..
        /// </summary>
        internal static string DoubleOutOfRange {
            get {
                return ResourceManager.GetString("DoubleOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for the enumeration is not on of the valid values..
        /// </summary>
        internal static string EnumerationOutOfRange {
            get {
                return ResourceManager.GetString("EnumerationOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The feature column values should be entered as string[] {&quot;Key1:Value1&quot;, &quot;Key2:Value2&quot;}.
        /// </summary>
        internal static string FeatureColumnValueDoesNotContainColon {
            get {
                return ResourceManager.GetString("FeatureColumnValueDoesNotContainColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Feature you provided is not valid..
        /// </summary>
        internal static string FeatureIsNotValid {
            get {
                return ResourceManager.GetString("FeatureIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Geometry Type Is Not Valid.
        /// </summary>
        internal static string InputGeometryTypeIsNotValid {
            get {
                return ResourceManager.GetString("InputGeometryTypeIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t Reorder for the multi-line because it does not satisfy the reorder condition based on the given startPoint and given tolerance..
        /// </summary>
        internal static string MultiLineCannotReorderForInputParams {
            get {
                return ResourceManager.GetString("MultiLineCannotReorderForInputParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t Reorder for the multi-line because it does not satisfy the reorder condition based on the given tolerance..
        /// </summary>
        internal static string MultiLineInvalidForReorder {
            get {
                return ResourceManager.GetString("MultiLineInvalidForReorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter you supplied may not be empty..
        /// </summary>
        internal static string ParameterIsEmpty {
            get {
                return ResourceManager.GetString("ParameterIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The shape you provided does not pass our simple validation..
        /// </summary>
        internal static string ParameterIsInvalid {
            get {
                return ResourceManager.GetString("ParameterIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter you supplied may not be null..
        /// </summary>
        internal static string ParameterIsNull {
            get {
                return ResourceManager.GetString("ParameterIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation&apos;s return type is not correct..
        /// </summary>
        internal static string ReturnTypeNotCorrect {
            get {
                return ResourceManager.GetString("ReturnTypeNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ring is not closed.  To close a ring the last point must be the same as the first point.  All rings must have at least four points..
        /// </summary>
        internal static string RingShapeIsInvalidForOperationVertexCountLessThan4 {
            get {
                return ResourceManager.GetString("RingShapeIsInvalidForOperationVertexCountLessThan4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation is not supported on this class..
        /// </summary>
        internal static string RotateNotSupported {
            get {
                return ResourceManager.GetString("RotateNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The shape you provided does not pass our simple validation..
        /// </summary>
        internal static string ShapeIsInvalidForOperation {
            get {
                return ResourceManager.GetString("ShapeIsInvalidForOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no points in the shape..
        /// </summary>
        internal static string ShapeIsInvalidForValidation {
            get {
                return ResourceManager.GetString("ShapeIsInvalidForValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Shape Is Not Valid Type..
        /// </summary>
        internal static string TargetShapeIsNotValidType {
            get {
                return ResourceManager.GetString("TargetShapeIsNotValidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value should be greater than zero..
        /// </summary>
        internal static string TheValueShouldBeGreaterThanZero {
            get {
                return ResourceManager.GetString("TheValueShouldBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format of the well known binary is incorrect..
        /// </summary>
        internal static string WkbIsInvalid {
            get {
                return ResourceManager.GetString("WkbIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The well known binary type is incorrect..
        /// </summary>
        internal static string WkbTypeError {
            get {
                return ResourceManager.GetString("WkbTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format of the well known text is incorrect..
        /// </summary>
        internal static string WktFormatIsWrong {
            get {
                return ResourceManager.GetString("WktFormatIsWrong", resourceCulture);
            }
        }
    }
}
