#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TestApp2.Resource", IsApplication=true)]

namespace TestApp2
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Mapgenix.GSuite.Android.Resource.Drawable.minus_blue_square = global::TestApp2.Resource.Drawable.minus_blue_square;
			global::Mapgenix.GSuite.Android.Resource.Drawable.plus_blue_square = global::TestApp2.Resource.Drawable.plus_blue_square;
			global::Mapgenix.GSuite.Android.Resource.Drawable.PowerBy = global::TestApp2.Resource.Drawable.PowerBy;
			global::Mapgenix.GSuite.Android.Resource.String.ApplicationName = global::TestApp2.Resource.String.ApplicationName;
			global::Mapgenix.GSuite.Android.Resource.String.Hello = global::TestApp2.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int minus_blue_square = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int normal61628 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int normal61629 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int normal61630 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int normal61728 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int normal61729 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int normal61730 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int plus_blue_square = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int PowerBy = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int MainLayout = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int MainMap = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int buttons = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int setTrack = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int unsetTrack = 2131034116;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int layout1 = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
