//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapgenix.FeatureSource.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionDescription {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionDescription() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mapgenix.FeatureSource.Properties.ExceptionDescription", typeof(ExceptionDescription).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The add transaction failed for an unknown reason..
        /// </summary>
        internal static string AddTransactionError {
            get {
                return ResourceManager.GetString("AddTransactionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can provide a path and file name to an icon or an image but not both..
        /// </summary>
        internal static string BothIconFilePathAndIconImageAreInvalid {
            get {
                return ResourceManager.GetString("BothIconFilePathAndIconImageAreInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cellHeight needs to be greater than zero..
        /// </summary>
        internal static string CellHeightLessThanZero {
            get {
                return ResourceManager.GetString("CellHeightLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cellWidth needs to be greater than zero..
        /// </summary>
        internal static string CellWidthLessThanZero {
            get {
                return ResourceManager.GetString("CellWidthLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not CloneDeep because the object is open or drawing, please close or end drawing first..
        /// </summary>
        internal static string CheckIsOpenedWhenCloneDeep {
            get {
                return ResourceManager.GetString("CheckIsOpenedWhenCloneDeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Layer must be opened before you can perform this method..
        /// </summary>
        internal static string CheckLayerIsOpened {
            get {
                return ResourceManager.GetString("CheckLayerIsOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current extent provided is not valid..
        /// </summary>
        internal static string CheckMapEngineCurrentExtentIsNotValid {
            get {
                return ResourceManager.GetString("CheckMapEngineCurrentExtentIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ClassBreak Number should be greater than one..
        /// </summary>
        internal static string ClassBreakNumberShouldBeGreaterThanOne {
            get {
                return ResourceManager.GetString("ClassBreakNumberShouldBeGreaterThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The class breaks you have provided are invalid..
        /// </summary>
        internal static string ClassBreaksIsValid {
            get {
                return ResourceManager.GetString("ClassBreaksIsValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The color you have provided does not exist..
        /// </summary>
        internal static string ColorDoesNotExist {
            get {
                return ResourceManager.GetString("ColorDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter column exceeds the total column count..
        /// </summary>
        internal static string ColumnNumberExceedTotalRowCount {
            get {
                return ResourceManager.GetString("ColumnNumberExceedTotalRowCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ImageSource is already open..
        /// </summary>
        internal static string CommonImageSourceIsAlreadyOpen {
            get {
                return ResourceManager.GetString("CommonImageSourceIsAlreadyOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection string can not be null..
        /// </summary>
        internal static string ConnectionStringCannotBeNull {
            get {
                return ResourceManager.GetString("ConnectionStringCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The creation of the shape file has failed..
        /// </summary>
        internal static string CreateShapeFileFailed {
            get {
                return ResourceManager.GetString("CreateShapeFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CurrentExtent property must be set before calling this method. If you want to use a custom extent, please use the static method.
        /// </summary>
        internal static string CurrentExtentNotAssigned {
            get {
                return ResourceManager.GetString("CurrentExtentNotAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already choose resize the image by custom size, please set the custom width and height..
        /// </summary>
        internal static string CustomImageSizeIsNull {
            get {
                return ResourceManager.GetString("CustomImageSizeIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DbfColumns collection is empty, you should add at least one DbfColumn when you create a new shape file..
        /// </summary>
        internal static string DbfColumnsIsEmpty {
            get {
                return ResourceManager.GetString("DbfColumnsIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The decimal degree latitude value you provided was out of range..
        /// </summary>
        internal static string DecimalDegreeLatitudeOutOfRange {
            get {
                return ResourceManager.GetString("DecimalDegreeLatitudeOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The decimal degree longitude value you provided was out of range..
        /// </summary>
        internal static string DecimalDegreeLongitudeOutOfRange {
            get {
                return ResourceManager.GetString("DecimalDegreeLongitudeOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The degreesMinutesSeconds string may not be null or empty..
        /// </summary>
        internal static string DecimalDegreeSecondsStringNull {
            get {
                return ResourceManager.GetString("DecimalDegreeSecondsStringNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DecimalLength is Invalid(it should be 0) for StringColumnType, it only make sense for DoubleColumnType..
        /// </summary>
        internal static string DecimalLengthInValidForStringColumnType {
            get {
                return ResourceManager.GetString("DecimalLengthInValidForStringColumnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are trying to use both a default style and the custom styles collection.  You may only use one or the other..
        /// </summary>
        internal static string DefaultAndCustomStyleDuplicate {
            get {
                return ResourceManager.GetString("DefaultAndCustomStyleDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are trying to use both a default style and the custom styles collection. If you want to add custom styles, please set RestrictionStyle as RestrictionStyle.UseCustomStyles..
        /// </summary>
        internal static string DefaultAndCustomStyleDuplicateForRestrictedLayer {
            get {
                return ResourceManager.GetString("DefaultAndCustomStyleDuplicateForRestrictedLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DegreesMinutesSeconds value is invalid..
        /// </summary>
        internal static string DegreesMinutesSecondsInputError {
            get {
                return ResourceManager.GetString("DegreesMinutesSecondsInputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The delete transaction failed for an unknown reason..
        /// </summary>
        internal static string DeleteTransactionError {
            get {
                return ResourceManager.GetString("DeleteTransactionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input double value is out of range..
        /// </summary>
        internal static string DoubleOutOfRange {
            get {
                return ResourceManager.GetString("DoubleOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have set IsEditable to true but have not overridden the CommitTransactionCore method.  Please override this the CommitTransactionCore method to prevent this exception..
        /// </summary>
        internal static string EditingNotSupported {
            get {
                return ResourceManager.GetString("EditingNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ellipse is not valid..
        /// </summary>
        internal static string EllipseIsNotValid {
            get {
                return ResourceManager.GetString("EllipseIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for the enumeration is not on of the valid values..
        /// </summary>
        internal static string EnumerationOutOfRange {
            get {
                return ResourceManager.GetString("EnumerationOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The evaluation edition has not been installed..
        /// </summary>
        internal static string EvalNotInstall {
            get {
                return ResourceManager.GetString("EvalNotInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The evaluation has expired.  Please contact Mapgenix for purchasing option or an extension to the trial..
        /// </summary>
        internal static string EvaluationExpired {
            get {
                return ResourceManager.GetString("EvaluationExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passed extent needs to intersect with the bounding box of the gid..
        /// </summary>
        internal static string ExtentNotIntersectsWithBoundingBox {
            get {
                return ResourceManager.GetString("ExtentNotIntersectsWithBoundingBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection of Features may not be empty..
        /// </summary>
        internal static string FeatureCollectionIsEmpty {
            get {
                return ResourceManager.GetString("FeatureCollectionIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The feature column values should be entered as string[] {&quot;Key1:Value1&quot;, &quot;Key2:Value2&quot;}.
        /// </summary>
        internal static string FeatureColumnValueDoesNotContainColon {
            get {
                return ResourceManager.GetString("FeatureColumnValueDoesNotContainColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The feature is invalid in in this style..
        /// </summary>
        internal static string FeatureIsInvalidInThisStyle {
            get {
                return ResourceManager.GetString("FeatureIsInvalidInThisStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Feature you provided is not valid..
        /// </summary>
        internal static string FeatureIsNotValid {
            get {
                return ResourceManager.GetString("FeatureIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing sql queries is not supported and the user should always check the CanExecuteSqlQueries to ensure the FeatureSource support it before calling..
        /// </summary>
        internal static string FeatureSourceCanNotExecuteSqlQuery {
            get {
                return ResourceManager.GetString("FeatureSourceCanNotExecuteSqlQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no FeatureSources..
        /// </summary>
        internal static string FeatureSourceCollectionIsEmpty {
            get {
                return ResourceManager.GetString("FeatureSourceCollectionIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection of FeatureSourceColumns may not be empty..
        /// </summary>
        internal static string FeatureSourceColumnCollectionIsEmpty {
            get {
                return ResourceManager.GetString("FeatureSourceColumnCollectionIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FeatureSource is already in a transaction..
        /// </summary>
        internal static string FeatureSourceIsAlreadyInTransaction {
            get {
                return ResourceManager.GetString("FeatureSourceIsAlreadyInTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FeatureSource is already opened..
        /// </summary>
        internal static string FeatureSourceIsAlreadyOpen {
            get {
                return ResourceManager.GetString("FeatureSourceIsAlreadyOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FeatureSource is not editable..
        /// </summary>
        internal static string FeatureSourceIsNotEditable {
            get {
                return ResourceManager.GetString("FeatureSourceIsNotEditable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FeatureSource is not in a transaction..
        /// </summary>
        internal static string FeatureSourceIsNotInTransaction {
            get {
                return ResourceManager.GetString("FeatureSourceIsNotInTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FeatureSource is not open.   Please call the Open method before calling this method..
        /// </summary>
        internal static string FeatureSourceIsNotOpen {
            get {
                return ResourceManager.GetString("FeatureSourceIsNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested column name is not in the Feature..
        /// </summary>
        internal static string FieldNameIsNotInFeature {
            get {
                return ResourceManager.GetString("FieldNameIsNotInFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File access error, you should open the shape file with ReadWrite mode..
        /// </summary>
        internal static string FileAccessError {
            get {
                return ResourceManager.GetString("FileAccessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file already exists..
        /// </summary>
        internal static string FileAlreadyExists {
            get {
                return ResourceManager.GetString("FileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file specified does not exist..
        /// </summary>
        internal static string FileIsNotExist {
            get {
                return ResourceManager.GetString("FileIsNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file type is not supported..
        /// </summary>
        internal static string FileIsSupportedByCommonImageSource {
            get {
                return ResourceManager.GetString("FileIsSupportedByCommonImageSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the fields in the database is not supported by SQL. The first character of this field name must be an alphabetic letter..
        /// </summary>
        internal static string FileNotSupportedForSql {
            get {
                return ResourceManager.GetString("FileNotSupportedForSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first ClassBreak value should be double.MinValue..
        /// </summary>
        internal static string FirstClassBreakValueError {
            get {
                return ResourceManager.GetString("FirstClassBreakValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GDI+ threw a status error code..
        /// </summary>
        internal static string GdipLoadImageFromFileError {
            get {
                return ResourceManager.GetString("GdipLoadImageFromFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The GeoCache is not open.  Please call the Open method before calling this method..
        /// </summary>
        internal static string GeoCacheIsNotOpen {
            get {
                return ResourceManager.GetString("GeoCacheIsNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The GeoCanvas is currently not drawing.  Please call the BeginDraw method before calling this method..
        /// </summary>
        internal static string GeocanvasIsNotInDrawing {
            get {
                return ResourceManager.GetString("GeocanvasIsNotInDrawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The map unit you are using is not compatable with the GoogleLayer .  Make sure you are using Meters and that your projection is 90013 to ensure compatability..
        /// </summary>
        internal static string GeographicUnitNotValidWithGoogle {
            get {
                return ResourceManager.GetString("GeographicUnitNotValidWithGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The map unit you are using is not compatable with the OpenStreetMap .  Make sure you are using Meters to ensure compatability with OpenStreetMap service..
        /// </summary>
        internal static string GeographicUnitNotValidWithOpenStreetMap {
            get {
                return ResourceManager.GetString("GeographicUnitNotValidWithOpenStreetMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input GeoImage object is not a valid GeoImage type..
        /// </summary>
        internal static string GeoImageIsNotValid {
            get {
                return ResourceManager.GetString("GeoImageIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have found geometries that are invalid according to the SQL Server STIsValid() Function. To automaticly fix these you can call the MakeAllGeometriesValid method. The SQL To Determine which records are invalid:.
        /// </summary>
        internal static string GeometriesInvalidExist {
            get {
                return ResourceManager.GetString("GeometriesInvalidExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometry type not recognized. .
        /// </summary>
        internal static string GeometrytypeIsWrong {
            get {
                return ResourceManager.GetString("GeometrytypeIsWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current GeoImage implementation does not support the GetSrid operation..
        /// </summary>
        internal static string GettingSridNotSupported {
            get {
                return ResourceManager.GetString("GettingSridNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must have at least one layer..
        /// </summary>
        internal static string GroupLayerIsEmpty {
            get {
                return ResourceManager.GetString("GroupLayerIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input string HtmlColor is invalid..
        /// </summary>
        internal static string HtmlColorIsInvalid {
            get {
                return ResourceManager.GetString("HtmlColorIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id column can&apos;t be null or empty..
        /// </summary>
        internal static string IdColumnCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("IdColumnCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection may not be empty or null..
        /// </summary>
        internal static string IEnumerableIsEmptyOrNull {
            get {
                return ResourceManager.GetString("IEnumerableIsEmptyOrNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image property can&apos;t be null..
        /// </summary>
        internal static string ImageInPointStyleCanNotBeNull {
            get {
                return ResourceManager.GetString("ImageInPointStyleCanNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ImageScaled property must be larger than 0..
        /// </summary>
        internal static string ImageScaleShouldBiggerThanZero {
            get {
                return ResourceManager.GetString("ImageScaleShouldBiggerThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ImageSource is already open..
        /// </summary>
        internal static string ImageSourceIsAlreadyOpen {
            get {
                return ResourceManager.GetString("ImageSourceIsAlreadyOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ImageSource is not open.  Please call the Open method before calling this method..
        /// </summary>
        internal static string ImageSourceIsNotOpen {
            get {
                return ResourceManager.GetString("ImageSourceIsNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index File already exist, please change the BuildIndexMode if you want to rebuild this index..
        /// </summary>
        internal static string IndexFileAlreadyExists {
            get {
                return ResourceManager.GetString("IndexFileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format of your index file is not valid, please check. Or you can use BuildIndexFile function to build a new one..
        /// </summary>
        internal static string IndexFileIsInvalid {
            get {
                return ResourceManager.GetString("IndexFileIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have the corresponding idx file for your shape file. You can use the static method ShapeFileFeatureSource.BuildIndexFile() or ShapeFileFeatureLayer.BuildIndexFile()  to build an idx file for the shape file, or you can set the RequireIndex property to false..
        /// </summary>
        internal static string IndexFileNotExisted {
            get {
                return ResourceManager.GetString("IndexFileNotExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Geometry Type Is Not Valid.
        /// </summary>
        internal static string InputGeometryTypeIsNotValid {
            get {
                return ResourceManager.GetString("InputGeometryTypeIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;re some invalid geometry instance in table not valid. About invalid geometry please have a look at http://msdn.microsoft.com/en-us/library/bb933890.aspx website. To solve this problem, we provide MakeAllGeometryValid function to make the invalid geometry to be valid, because of the function updating your data, you need to backup your data before using this function..
        /// </summary>
        internal static string InvalidGeometryInMsSqlForSpatialQuery {
            get {
                return ResourceManager.GetString("InvalidGeometryInMsSqlForSpatialQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Operation Exception..
        /// </summary>
        internal static string InvalidOperationExceptionError {
            get {
                return ResourceManager.GetString("InvalidOperationExceptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is not supported now for projection..
        /// </summary>
        internal static string IsNotSupportedNowForProjection {
            get {
                return ResourceManager.GetString("IsNotSupportedNowForProjection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The GeoCollection does not contain the item you specified..
        /// </summary>
        internal static string ItemNotFoundInGeoCollectionByItem {
            get {
                return ResourceManager.GetString("ItemNotFoundInGeoCollectionByItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The GeoCollection does not contain the item you specified..
        /// </summary>
        internal static string ItemNotFoundInGeoCollectionByKey {
            get {
                return ResourceManager.GetString("ItemNotFoundInGeoCollectionByKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value should be between zero and one hundred..
        /// </summary>
        internal static string JpegImageCompressionShouldBeBetweenZeroAndOneHundred {
            get {
                return ResourceManager.GetString("JpegImageCompressionShouldBeBetweenZeroAndOneHundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not support KeyColor in the specify GeoCanvas..
        /// </summary>
        internal static string KeyColorIsNotSupported {
            get {
                return ResourceManager.GetString("KeyColorIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Layer doesn&apos;t have a boundingBox..
        /// </summary>
        internal static string LayerDoesNotHaveBoundingBox {
            get {
                return ResourceManager.GetString("LayerDoesNotHaveBoundingBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The layer type you have provided is not valid..
        /// </summary>
        internal static string LayersTypeIsOutOfRange {
            get {
                return ResourceManager.GetString("LayersTypeIsOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current extent you have provided is not valid..
        /// </summary>
        internal static string MapEngineCurrentExtentIsNotValid {
            get {
                return ResourceManager.GetString("MapEngineCurrentExtentIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current extent you have provided may not be null..
        /// </summary>
        internal static string MapEngineCurrentExtentIsNull {
            get {
                return ResourceManager.GetString("MapEngineCurrentExtentIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input MGRS string is invalid..
        /// </summary>
        internal static string MGRSInvalid {
            get {
                return ResourceManager.GetString("MGRSInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MrSidGeoImageSource is already open..
        /// </summary>
        internal static string MrSidGeoImageSourceIsAlreadyOpen {
            get {
                return ResourceManager.GetString("MrSidGeoImageSourceIsAlreadyOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MrSidGeoImageSource is not open.  Please open it before calling this method..
        /// </summary>
        internal static string MrSidGeoImageSourceIsNotOpen {
            get {
                return ResourceManager.GetString("MrSidGeoImageSourceIsNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format of Multi-FieldNames isn&apos;t correct..
        /// </summary>
        internal static string MultiFieldNamesNotSupportedError {
            get {
                return ResourceManager.GetString("MultiFieldNamesNotSupportedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t Reorder for the multi-line because it does not satisfy the reorder condition based on the given startPoint and given tolerance..
        /// </summary>
        internal static string MultiLineCannotReorderForInputParams {
            get {
                return ResourceManager.GetString("MultiLineCannotReorderForInputParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t Reorder for the multi-line because it does not satisfy the reorder condition based on the given tolerance..
        /// </summary>
        internal static string MultiLineInvalidForReorder {
            get {
                return ResourceManager.GetString("MultiLineInvalidForReorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all valid layers are open..
        /// </summary>
        internal static string NotAllValidLayersAreOpen {
            get {
                return ResourceManager.GetString("NotAllValidLayersAreOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature is currently not supported..
        /// </summary>
        internal static string NotSupported {
            get {
                return ResourceManager.GetString("NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file type you provided is currently not supported..
        /// </summary>
        internal static string NotSupportedFileType {
            get {
                return ResourceManager.GetString("NotSupportedFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SQL Query mode is not supported..
        /// </summary>
        internal static string NotSupportedSqlQueryMode {
            get {
                return ResourceManager.GetString("NotSupportedSqlQueryMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number should be between 0 and 255.
        /// </summary>
        internal static string NumberShouldBeByte {
            get {
                return ResourceManager.GetString("NumberShouldBeByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We cannot get the AreaUnit from input unit..
        /// </summary>
        internal static string ParameterCanNotConvert {
            get {
                return ResourceManager.GetString("ParameterCanNotConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Ids should be from 1 to the record number in ShapeFileFeatureSource.
        /// </summary>
        internal static string ParameterIdsIsNotIntegers {
            get {
                return ResourceManager.GetString("ParameterIdsIsNotIntegers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter you supplied may not be empty..
        /// </summary>
        internal static string ParameterIsEmpty {
            get {
                return ResourceManager.GetString("ParameterIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The shape you provided does not pass our simple validation..
        /// </summary>
        internal static string ParameterIsInvalid {
            get {
                return ResourceManager.GetString("ParameterIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter you supplied may not be null..
        /// </summary>
        internal static string ParameterIsNull {
            get {
                return ResourceManager.GetString("ParameterIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter is transparent..
        /// </summary>
        internal static string ParameterIsTransparent {
            get {
                return ResourceManager.GetString("ParameterIsTransparent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer layer supports Feet or Meter only.
        /// </summary>
        internal static string PrinterLayerGeographyUnitDoesNotSupported {
            get {
                return ResourceManager.GetString("PrinterLayerGeographyUnitDoesNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projection initialization failed..
        /// </summary>
        internal static string ProjectionInitializationError {
            get {
                return ResourceManager.GetString("ProjectionInitializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get the projection’s InternalGeographyUnit, please provide it by overriding the Projection’s GetInternalGeographyUnitCore() method..
        /// </summary>
        internal static string ProjectionInternalGeographyIsUnknown {
            get {
                return ResourceManager.GetString("ProjectionInternalGeographyIsUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The projection is not open.  Please open it before calling this method..
        /// </summary>
        internal static string ProjectionIsNotOpen {
            get {
                return ResourceManager.GetString("ProjectionIsNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This RasterLayer does not have projection information embedded in it.  If you wish to avoid this exception you can first check the HasProjectionTextProperty..
        /// </summary>
        internal static string RasterLayerDoesNotHaveProjectionInformation {
            get {
                return ResourceManager.GetString("RasterLayerDoesNotHaveProjectionInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This RasterSource does not have projection information embedded in it.  If you wish to avoid this exception you can first check the HasProjectionTextProperty..
        /// </summary>
        internal static string RasterSourceNotContainsProjectionInformation {
            get {
                return ResourceManager.GetString("RasterSourceNotContainsProjectionInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rebuild of the DBF failed for an unknown reason.  Please see the inner exception..
        /// </summary>
        internal static string RebuildDbfFailed {
            get {
                return ResourceManager.GetString("RebuildDbfFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The spatial index generation failed for an unknown reason.    Please see the inner exception..
        /// </summary>
        internal static string RebuildIdxFailed {
            get {
                return ResourceManager.GetString("RebuildIdxFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the rebuilding of the shape file failed for an unknown reason.    Please see the inner exception..
        /// </summary>
        internal static string RebuildShapeFileFailed {
            get {
                return ResourceManager.GetString("RebuildShapeFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record is invalid, please call Validate method to check the failed reason..
        /// </summary>
        internal static string RecordIsInvalid {
            get {
                return ResourceManager.GetString("RecordIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation&apos;s return type is not correct..
        /// </summary>
        internal static string ReturnTypeNotCorrect {
            get {
                return ResourceManager.GetString("ReturnTypeNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return value is null..
        /// </summary>
        internal static string ReturnValueIsNull {
            get {
                return ResourceManager.GetString("ReturnValueIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ring is not closed.  To close a ring the last point must be the same as the first point.  All rings must have at least four points..
        /// </summary>
        internal static string RingShapeIsInvalidForOperationVertexCountLessThan4 {
            get {
                return ResourceManager.GetString("RingShapeIsInvalidForOperationVertexCountLessThan4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation is not supported on this class..
        /// </summary>
        internal static string RotateNotSupported {
            get {
                return ResourceManager.GetString("RotateNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter row exceeds the total row count..
        /// </summary>
        internal static string RowNumberExceedTotalRowCount {
            get {
                return ResourceManager.GetString("RowNumberExceedTotalRowCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The RtreeSpatialIndex is not open.   Please call the Open method before calling this method..
        /// </summary>
        internal static string RtreeSpatialIndexIsNotOpen {
            get {
                return ResourceManager.GetString("RtreeSpatialIndexIsNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The shape file bounding box is invalid..
        /// </summary>
        internal static string ShapeFileBoundingBoxIsValid {
            get {
                return ResourceManager.GetString("ShapeFileBoundingBoxIsValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Shapefile Id is one based, zero is an invalid Id..
        /// </summary>
        internal static string ShapefileFeatureSourceIdNotFromZero {
            get {
                return ResourceManager.GetString("ShapefileFeatureSourceIdNotFromZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An InnerRing doesn&apos;t contained in any OuterRing. .
        /// </summary>
        internal static string ShapeFileInnerRingNotContainedInOuterRing {
            get {
                return ResourceManager.GetString("ShapeFileInnerRingNotContainedInOuterRing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The shape file name is invalid..
        /// </summary>
        internal static string ShapeFileNameIsInvalid {
            get {
                return ResourceManager.GetString("ShapeFileNameIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The shape you provided does not pass our simple validation..
        /// </summary>
        internal static string ShapeIsInvalidForOperation {
            get {
                return ResourceManager.GetString("ShapeIsInvalidForOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no points in the shape..
        /// </summary>
        internal static string ShapeIsInvalidForValidation {
            get {
                return ResourceManager.GetString("ShapeIsInvalidForValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This shape has not been implemented yet..
        /// </summary>
        internal static string ShapeTypeNotImplement {
            get {
                return ResourceManager.GetString("ShapeTypeNotImplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The shape file index is not open..
        /// </summary>
        internal static string ShxFileIsNotOpen {
            get {
                return ResourceManager.GetString("ShxFileIsNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The features in SpatialIndex are not removable..
        /// </summary>
        internal static string SpatialIndexIsNotRemovable {
            get {
                return ResourceManager.GetString("SpatialIndexIsNotRemovable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input srid is not valid..
        /// </summary>
        internal static string SridIsInvalid {
            get {
                return ResourceManager.GetString("SridIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream is not writable..
        /// </summary>
        internal static string StreamIsNotWritable {
            get {
                return ResourceManager.GetString("StreamIsNotWritable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input string value is not blank..
        /// </summary>
        internal static string StringIsNotBlank {
            get {
                return ResourceManager.GetString("StringIsNotBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The corresponding idx/ids file cannot be found. Please use the static method TabFeatureSource.BuildIndexFile() or TabFeatureLayer.BuildIndexFile() to build the idx/ids file, which can greatly improve the querying performance. If the RequireIndex Property is set to false, the idx/ids files will not be checked and an internal spatial index will be created instead..
        /// </summary>
        internal static string TabIndexFileNotExisted {
            get {
                return ResourceManager.GetString("TabIndexFileNotExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Shape Is Not Valid Type..
        /// </summary>
        internal static string TargetShapeIsNotValidType {
            get {
                return ResourceManager.GetString("TargetShapeIsNotValidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field type should be numeric..
        /// </summary>
        internal static string TheFieldTtypeShouldBeNumeric {
            get {
                return ResourceManager.GetString("TheFieldTtypeShouldBeNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format of the image is not supported..
        /// </summary>
        internal static string TheFormatOfImageIsNotSupported {
            get {
                return ResourceManager.GetString("TheFormatOfImageIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value should be greater than zero..
        /// </summary>
        internal static string TheValueShouldBeGreaterThanZero {
            get {
                return ResourceManager.GetString("TheValueShouldBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlicensed..
        /// </summary>
        internal static string Unlicensed {
            get {
                return ResourceManager.GetString("Unlicensed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently we do not support editing this kind of shape type. Shape type:.
        /// </summary>
        internal static string UnsupportedEditingShapeType {
            get {
                return ResourceManager.GetString("UnsupportedEditingShapeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update transaction failed for an unknown reason..
        /// </summary>
        internal static string UpdateTansactionError {
            get {
                return ResourceManager.GetString("UpdateTansactionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input Uri is not valid.
        /// </summary>
        internal static string UriNotValid {
            get {
                return ResourceManager.GetString("UriNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The TIFF files(.tif or .tiff) are not supported in GdiPlusRasterSource any longer, please use the GeoTiffRasterSource instead..
        /// </summary>
        internal static string UseGeoTiffRasterInstead {
            get {
                return ResourceManager.GetString("UseGeoTiffRasterInstead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format of the well known binary is incorrect..
        /// </summary>
        internal static string WkbIsInvalid {
            get {
                return ResourceManager.GetString("WkbIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The well known binary is not valid for drawing..
        /// </summary>
        internal static string WkbIsNotValidForDrawing {
            get {
                return ResourceManager.GetString("WkbIsNotValidForDrawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The well known binary type is incorrect..
        /// </summary>
        internal static string WkbTypeError {
            get {
                return ResourceManager.GetString("WkbTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format of the well known text is incorrect..
        /// </summary>
        internal static string WktFormatIsWrong {
            get {
                return ResourceManager.GetString("WktFormatIsWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinate Reference System not set..
        /// </summary>
        internal static string WmsCRSNotSet {
            get {
                return ResourceManager.GetString("WmsCRSNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This CRS is not supported in the Wms server: .
        /// </summary>
        internal static string WmsCRSNotSupport {
            get {
                return ResourceManager.GetString("WmsCRSNotSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Wms server has timed out..
        /// </summary>
        internal static string WmsGetMapTimeOut {
            get {
                return ResourceManager.GetString("WmsGetMapTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Wms request LAYERS parameter is missing..
        /// </summary>
        internal static string WmsLayerDoesNotExists {
            get {
                return ResourceManager.GetString("WmsLayerDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No layers exist in the Service Description..
        /// </summary>
        internal static string WmsNoLayerExists {
            get {
                return ResourceManager.GetString("WmsNoLayerExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested parameter does not exists in this Service Description..
        /// </summary>
        internal static string WmsRequestParaNotExists {
            get {
                return ResourceManager.GetString("WmsRequestParaNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This image format is not supported in the Wms server: .
        /// </summary>
        internal static string WmsServerNotSupportFormat {
            get {
                return ResourceManager.GetString("WmsServerNotSupportFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This layer is not supported in the Wms server: .
        /// </summary>
        internal static string WmsServerNotSupportLayer {
            get {
                return ResourceManager.GetString("WmsServerNotSupportLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This style is not supported in the Wms server: .
        /// </summary>
        internal static string WmsServerNotSupportStyle {
            get {
                return ResourceManager.GetString("WmsServerNotSupportStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Wms request STYLES parameter is missing..
        /// </summary>
        internal static string WmsStyleDoesNotExists {
            get {
                return ResourceManager.GetString("WmsStyleDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The world extent is not valid..
        /// </summary>
        internal static string WorldExtentIsNotValid {
            get {
                return ResourceManager.GetString("WorldExtentIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World file should has 6 lines..
        /// </summary>
        internal static string WorldFileShould6Lines {
            get {
                return ResourceManager.GetString("WorldFileShould6Lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ImageSource is already open..
        /// </summary>
        internal static string WpfCommonGeoImageSourceIsAlreadyOpen {
            get {
                return ResourceManager.GetString("WpfCommonGeoImageSourceIsAlreadyOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ImageSource is not opened.  Please open it before calling this method..
        /// </summary>
        internal static string WpfCommonGeoImageSourceIsNotOpen {
            get {
                return ResourceManager.GetString("WpfCommonGeoImageSourceIsNotOpen", resourceCulture);
            }
        }
    }
}
